spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE/
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/login

eureka:
  instance:
    hostname: localhost

server:
  port: 8222