spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/** , /api/v1/login
        - id: payment-gateway-service
          uri: lb://PAYMENT-GATEWAY-SERVICE
          predicates:
            - Path=/api/v1/payment/**
eureka:
  instance:
    hostname: localhost
api:
  prefix: "/api/v1"

server:
  port: 8222