spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/** , /api/authentication/**, /internal/user**
        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/api/v1/billing/**
        - id: payment-gateway-service
          uri: lb://PAYMENT-GATEWAY-SERVICE
          predicates:
            - Path=/api/v1/payment/**
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transaction/**

eureka:
  instance:
    hostname: localhost
api:
  user-service-url: "http://localhost:8090"
  prefix: "/api"

server:
  port: 8222