spring:
  data:
    mongodb:
      uri: mongodb://root:admin@localhost:27017/notification-service?authSource=admin
#      uri: mongodb://root:Admin%40123@localhost:27018/notification-service?authSource=admin
#    mongodb:
#      username: root
#      password: admin
#      host: localhost
#      port: 27017
#      database: notification-service
#      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
#        spring.json.type.mapping: orderConfirmation:com.hpbt.notificationservice.kafka.OrderConfirmation,paymentConfirmation:com.hpbt.notificationservice.kafka.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: duesjacky
    password: duesjacky
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8094
