spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/transactionservice
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-version: 0
    baseline-description: "init database"

server:
  port: 8092