-- create table if not exists "user" (
--     id serial primary key,
--     username varchar(255) unique not null,
--     password varchar(255) not null,
--     user_role varchar(255) not null,
--     email varchar(255) unique not null,
--     full_name varchar(255) not null,
--     avatar varchar(255) null,
--     created_at timestamptz default current_timestamp,
--     updated_at timestamptz default current_timestamp
-- );
--
-- create table if not exists access_key (
--     id serial primary key,
--     api_key varchar(255) unique not null,
--     status varchar(255) not null,
--     expires_at timestamptz,
--     created_at timestamptz default current_timestamp,
--     revoked_at timestamptz,
--     user_id int not null,
--     constraint fk_user foreign key (user_id) references "user"(id) on delete cascade
-- );
